name: CI - Spring Boot (Maven + SonarCloud)

on:
  pull_request:
    branches: [ "develop" ]

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build, Test & Analyze (Java 17)
    runs-on: ubuntu-latest

    # Necesario para que SonarCloud pueda decorar el PR
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Recomendado por SonarCloud para tener info de historial
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build, Test & SonarCloud analysis
        env:
          # Token definido en Settings > Secrets and variables > Actions
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Token de GitHub para que SonarCloud pueda comentar/decorar el PR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B -ntp clean verify \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=leadiaz \
            -Dsonar.projectKey=compra-tu-auto-app-backend
